# .circleci/config.yml
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
      - store_test_results:
          path: ~/project/junit.xml

  android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-26-node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: bundle install
      - run: bundle exec fastlane test
      - store_test_results:
          path: ~/project/android/reports


workflows:
  version: 2
  node-android:
    jobs:
      - build
      - android:
          requires:
            - build
